# Site Settings
title: Sumit Srivastava
name: 'Sumit Srivastava'
description: 'Research • Software Development • Philosophy • Food'

# Google Analytics
google_analytics: G-XXXXXXXXXX # Replace with your Google Analytics tracking ID
baseurl: ""
url: "https://sumitsrv.github.io"
logo: 'assets/images/picofme5.png'
favicon: 'assets/images/favicon.ico'
email: 'srv.sumit@gmail.com'
disqus: 'sumitsrv-github-io'

# Social Media Links
social:
  linkedin: https://www.linkedin.com/in/sumit-srv
  github: https://github.com/sumitsrv
  google_scholar: https://scholar.google.com/citations?user=cQhsN6IAAAAJ&hl=en
  instagram: https://www.instagram.com/srvsumit/
  twitter: https://x.com/SumSrvt

# Navigation
navigation:
  - title: About
    url: /
  - title: Research
    url: /research/
  - title: Software
    url: /software/
  - title: Philosophy
    url: /philosophy/
  - title: Food
    url: /food/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 6
paginate_path: /page:num/

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - .git/

# Performance Settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ["development"]
  blanklines: false
  profile: false

# SEO & Social Sharing
twitter:
  username: sumsrvt
  card: summary_large_image

# Plugins (GitHub Pages compatible)
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Progressive Web App
pwa:
  enabled: true
  sw_filename: service-worker.js
  sw_src_filepath: service-worker.js
  dest_js_directory: assets/js
  precache_recent_posts_num: 5
  precache_glob_patterns:
    - "assets/css/*.css"
    - "assets/js/*.js"
  
authors:
    sumit:
      name:           Sumit
      site:           https://sumitsrv.github.io
      avatar:         assets/images/picofme5.png
      bio:            "Hi, I am Sumit, and I think sometimes, often blah, I hope you like it!"
      email:  srv.sumit@gmail.com
      twitter:        https://twitter.com/sumsrvt
      social:
        name: Sumit Srivastava
        links:
          - https://www.linkedin.com/in/sumit-srv/
 
# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: modern-post
      author: sumit
      avatar: /assets/images/picofme5.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: modern-default
      
# Theme Settings
theme_skin: classic # classic, dark, modern
dark_mode_toggle: true
enable_search: true

# Content Settings
show_excerpts: true
reading_time: true
show_related_posts: true
show_post_categories: true
show_post_tags: true
enable_social_sharing: true


# Exclude metadata and development time dependencies (like Grunt plugins)
include:
  - "_pages"
  
exclude: 
  - README.markdown
  - package.json
  - grunt.js
  - Gruntfile.js
  - Gruntfile.coffee
  - node_modules
  - vendor/
  - Gemfile
  - Gemfile.lock
  - "**/*.erb"
  - "**/site_template/**"
