# Site
title: I Think Blah
name: 'I Think Blah'
description: Follow me
baseurl: ""
url: "" #jhkjhk
logo: 'assets/images/tree_thinking_blah_mc.png'
favicon: 'assets/images/favicon.ico'
email: 'srv.sumit@gmail.com'
include: ["_pages"]
disqus: 'sumitsrv-github-io'
permalink: /:title/


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sumit:
      name:           Sumit
      site:           https://sumitsrv.github.io
      avatar:         assets/images/picofme5.png
      bio:            "Hi, I am Sumit, and I think sometimes, often blah, I hope you like it!"
      email:  srv.sumit@gmail.com
      twitter:        https://twitter.com/sumsrvt
      social:
        name: Sumit Srivastava
        links:
          - https://www.linkedin.com/in/sumit-srv/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sumit
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
